manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: heinn-dev
      url-base: https://github.com/heinn-dev
    - name: oleksandrmaslov
      url-base: https://github.com/oleksandrmaslov     
      
  projects:
    - name: zmk
      remote: heinn-dev
      revision: main
      import: app/west.yml
    - name: zmk-analog-input-driver
      remote: badjeff
      revision: main
    - name: zmk-pointing-acceleration
      remote: oleksandrmaslov
      revision: main
      
  self:
    path: config